metrics:
  scale_factor:
  - 1.0
  - 2.0
  - 2.0
  resolution: 512
optimizations:
  use_torch_compile: true
  use_flash_attention: true
model:
  checkpoint_path: ai-forever/Kandinsky-5.0-T2V-Lite-nocfg-5s
  num_steps: 50
  guidance_weight: 1.0
  duration: 5
  dit_params:
    in_visual_dim: 16
    out_visual_dim: 16
    time_dim: 512
    patch_size:
    - 1
    - 2
    - 2
    model_dim: 1792
    ff_dim: 7168
    num_text_blocks: 2
    num_visual_blocks: 32
    axes_dims:
    - 16
    - 24
    - 24
    visual_cond: true
    in_text_dim: 3584
    in_text_dim2: 768
  attention:
    type: flash
    causal: false
    local: false
    glob: false
    window: 3
  vae:
    checkpoint_path: "hunyuanvideo-community/HunyuanVideo"
    name: "hunyuan"
    tile_threshold: 450
  text_embedder:
    qwen: 
      emb_size: 3584
      checkpoint_path: "Qwen/Qwen2.5-VL-7B-Instruct"
      max_length: 256
    clip:
      checkpoint_path: "openai/clip-vit-large-patch14"
      emb_size: 768
      max_length: 77
